import type { AppCategory } from "../attention/types";

const categoryByApp: Record<string, AppCategory> = {
  arc: "browser",
  behance: "productivity",
  bitbucket: "development",
  "bluesky": "social",
  "canva": "productivity",
  "claude": "development",
  "claude code": "development",
  "codex": "development",
  "codex cli": "development",
  comet: "browser",
  "crates.io": "development",
  cursor: "development",
  "discord": "communication",
  "disney+": "entertainment",
  "docker hub": "development",
  "docs.rs": "development",
  dribbble: "productivity",
  facebook: "social",
  figma: "productivity",
  firefox: "browser",
  framer: "productivity",
  "git": "development",
  github: "development",
  gitlab: "development",
  "gmail": "communication",
  "google chat": "communication",
  "google chrome": "browser",
  "google calendar": "communication",
  "google docs": "browser",
  "google drive": "browser",
  "google meet": "communication",
  "google search": "browser",
  "google sheets": "browser",
  "google slides": "browser",
  hotstar: "entertainment",
  instagram: "social",
  linkedin: "social",
  learning: "learning",
  "mdn web docs": "development",
  "microsoft teams": "communication",
  netflix: "entertainment",
  notion: "productivity",
  obsidian: "productivity",
  todoist: "productivity",
  things: "productivity",
  linear: "productivity",
  jira: "productivity",
  trello: "productivity",
  airtable: "productivity",
  asana: "productivity",
  evernote: "productivity",
  bear: "productivity",
  craft: "productivity",
  "npmjs": "development",
  outlook: "communication",
  "openai atlas": "browser",
  atlas: "browser",
  perplexity: "browser",
  "prime video": "entertainment",
  pypi: "development",
  reddit: "social",
  safari: "browser",
  sketch: "productivity",
  slack: "communication",
  spotify: "entertainment",
  "stack overflow": "development",
  threads: "social",
  tiktok: "social",
  twitch: "entertainment",
  twitter: "social",
  "visual studio code": "development",
  vscode: "development",
  terminal: "development",
  iterm: "development",
  chrome: "browser",
  youtube: "entertainment",
  webflow: "productivity",
  wikipedia: "browser",
  x: "social",
};

export function categorizeApp(appName: string): AppCategory {
  const normalized = appName.trim().toLowerCase();

  if (normalized.startsWith("terminal:") || normalized.startsWith("iterm2:")) {
    return "development";
  }

  const categoryTarget = normalized.split(": ").at(1) ?? normalized;

  return categoryByApp[categoryTarget] ?? "unknown";
}
